apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: default
spec:
  replicas: {{ .Values.app1.replicaCount }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: dejanualex/flaskapp:1.0
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis"  # This should match the name of the Redis service
            - name: REDIS_PORT
              value: "6379"