version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes: 
      - cache:/data # mount cache volume inside redis container at path /data

  python-app:
    build:
      context: .
    container_name: flask-app
    depends_on:
      - redis
    ports:
      - "5000:5000"
    restart: always

volumes: # define volume local fs 
  cache:
    driver: local