# Global configurations
global:
  imagePullSecrets: []
  # Add any global settings here, if applicable

# Configuration for Deployment 1 (app1)
app1:
  replicaCount: 1

# Configuration for Deployment 2 (app2)
