name: Linting|Testing|Build

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*" # Trigger on semever tags
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 pytest
        if [ -f ./python_hello_app/requirements.txt ]; then pip install -r ./python_hello_app/requirements.txt; fi
    - name: Linting with pylint
      continue-on-error: true
      run: |
        pylint $(git ls-files '*.py')
    - name: unit-testing with unittest
      run: |
        pytest python_hello_app/test_app.py 
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') # Ensure the build runs only for tag pushes
    steps:
    # - name: Docker meta
    #   id: meta
    #   uses: docker/metadata-action@v5
    #   with:
    #     images: |
    #       dejanualex/course
    #       docker.io/dejanualex/course
    #     tags: |
    #       type=schedule
    #       type=ref,event=branch
    #       type=ref,event=pr
    #       type=semver,pattern={{version}}
    #       type=semver,pattern={{major}}.{{minor}}
    #       type=semver,pattern={{major}}
    #       type=sha            
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Extract Git Tag
      id: extract_tag
      run: echo "IMAGE_TAG=${GITHUB_REF##refs/tags/}" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:python_hello_app"
        push: true
        tags:
          dejanualex/pythonhello:${{ env.IMAGE_TAG }}
          # docker.io/dejanualex/pythonhello:${{ env.IMAGE_TAG }}

        # tags: dejanualex/pythonhello:1.0
